//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.ServicioReferencia1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioReferencia1.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarTTiempo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarTTiempo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarTTiempo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarTTiempoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarDepartamento(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarDepartamentoAsync(string Nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : ClienteWeb.ServicioReferencia1.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<ClienteWeb.ServicioReferencia1.ServicioWebSoap>, ClienteWeb.ServicioReferencia1.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarTTiempo() {
            return base.Channel.ListarTTiempo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarTTiempoAsync() {
            return base.Channel.ListarTTiempoAsync();
        }
        
        public System.Data.DataSet ListarDepartamento(string Nombre) {
            return base.Channel.ListarDepartamento(Nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarDepartamentoAsync(string Nombre) {
            return base.Channel.ListarDepartamentoAsync(Nombre);
        }
    }
}
