'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServicioReferencia1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioReferencia1.ServicioWebSoap")>  _
    Public Interface ServicioWebSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarTTiempo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarTTiempo() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarTTiempo", ReplyAction:="*")>  _
        Function ListarTTiempoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicioWebSoapChannel
        Inherits ServicioReferencia1.ServicioWebSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioWebSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioReferencia1.ServicioWebSoap)
        Implements ServicioReferencia1.ServicioWebSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarTTiempo() As System.Data.DataSet Implements ServicioReferencia1.ServicioWebSoap.ListarTTiempo
            Return MyBase.Channel.ListarTTiempo
        End Function
        
        Public Function ListarTTiempoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServicioReferencia1.ServicioWebSoap.ListarTTiempoAsync
            Return MyBase.Channel.ListarTTiempoAsync
        End Function
    End Class
End Namespace
